### ISSUE TITLE
The name of the subcommand `moon info` is not clear

### ISSUE THREAD

**Issue by lgxbslgx** [moonbitlang/moon#299]
The subcommand `moon info` can generate public interface (`.mbti`) files for all packages in the module. But the name `info` seems a abbreviation of the `information`. Why did we use such name? Does it mean: the interface is the module information? Whatever, I think this name is strange and not clear. Can we change it to names like `generate-interface`, `gen-interface`, `interface` or else.

**Comment by lgxbslgx** [comment]
Should I ask this problem in the `Discussions` instead of the `Issues`? If so, sorry for that.

**Comment by lijunchen** [comment]
> Should I ask this problem in the Discussions instead of the Issues? If so, sorry for that.

Feel free. there isn't any established convention on this yet.

> Why did we use such name?

It's simply because it calls the `mooninfo` binary :)

The initial purpose of `mooninfo` was to make it easier to review the public members of packages in `moonbitlang/core`. The term "info" is preferred because it is not an interface file. Mbti files don't have any meaning, just text files.

**Comment by lgxbslgx** [comment]
Thanks for your answer.
